In [1]:
import numpy as np
import pandas as pd

loading users dataset

In [2]:
df_users = pd.read_csv("BX-Users.csv", encoding='latin-1')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9072\856297225.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_users = pd.read_csv("BX-Users.csv", encoding='latin-1')


In [3]:
df_users.head()

user_id                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

In [4]:
df_users.shape

(278859, 3)

In [5]:
df_users.isnull().sum()

user_id          0
Location         1
Age         110763
dtype: int64

In [6]:
df_users.isnull().any()

user_id     False
Location     True
Age          True
dtype: bool

In [7]:
df_users1 = df_users.dropna()

In [8]:
df_users1.isnull().sum()

user_id     0
Location    0
Age         0
dtype: int64

loading books dataset

In [9]:
df_books = pd.read_csv('BX-Books.csv',encoding='latin-1')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9072\1159819802.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_books = pd.read_csv('BX-Books.csv',encoding='latin-1')


In [10]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271379 entries, 0 to 271378
Data columns (total 5 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   isbn                 271379 non-null  object
 1   book_title           271379 non-null  object
 2   book_author          271378 non-null  object
 3   year_of_publication  271379 non-null  object
 4   publisher            271377 non-null  object
dtypes: object(5)
memory usage: 10.4+ MB


In [11]:
df_books.head()

isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [12]:
df_books.shape

(271379, 5)

In [13]:
df_books.isnull().sum()

isbn                   0
book_title             0
book_author            1
year_of_publication    0
publisher              2
dtype: int64

loading ratings dataset. loading only 10000 ratings due to memory constraints

In [14]:
df_ratings = pd.read_csv('BX-Book-Ratings.csv',encoding='latin-1',nrows=10000)

In [15]:
df_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   user_id  10000 non-null  int64 
 1   isbn     10000 non-null  object
 2   rating   10000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 234.5+ KB


In [16]:
df_ratings.head()

user_id        isbn  rating
0   276725  034545104X       0
1   276726   155061224       5
2   276727   446520802       0
3   276729  052165615X       3
4   276729   521795028       6

In [17]:
df_ratings.isnull().sum()

user_id    0
isbn       0
rating     0
dtype: int64

In [18]:
df_ratings.describe()

user_id        rating
count   10000.000000  10000.000000
mean   265844.379600      1.974700
std     56937.189618      3.424884
min         2.000000      0.000000
25%    277478.000000      0.000000
50%    278418.000000      0.000000
75%    278418.000000      4.000000
max    278854.000000     10.000000

merge books and ratings datasets on isbn

In [19]:
df_final = pd.merge(df_ratings,df_books, on='isbn')

In [20]:
df_final.head()

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  
0                2002            Ballantine Books  
1                2001                      Heinle  
2                1996                Warner Books  
3                1996                Warner Books  
4                1999  Cambridge University Press

In [21]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8701 entries, 0 to 8700
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   user_id              8701 non-null   int64 
 1   isbn                 8701 non-null   object
 2   rating               8701 non-null   int64 
 3   book_title           8701 non-null   object
 4   book_author          8701 non-null   object
 5   year_of_publication  8701 non-null   object
 6   publisher            8701 non-null   object
dtypes: int64(2), object(5)
memory usage: 543.8+ KB


Take a quick look at the number of unique users and books

In [22]:
users = df_final['user_id'].nunique()
books = df_final['isbn'].nunique()

print('No. of users', str(users))
print('No. of books', str(books))

No. of users 828
No. of books 8051


Convert ISBN variables to numeric numbers in the correct order

In [23]:
isbn_list = df_final['isbn'].unique()
print('length of isbn:', len(isbn_list))
def get_isbn_numeric_id(isbn):
    item_index = np.where(isbn_list==isbn)
    return item_index[0][0]

length of isbn: 8051


Convert the user_id variable to numeric numbers in the correct order

In [25]:
userid_list = df_final['user_id'].unique()
print('length of userid_list:', len(userid_list))
def get_user_numeric_id(user_id):
    item_index = np.where(userid_list==user_id)
    return item_index[0][0]

length of userid_list: 828


Convert both user_id and ISBN to the ordered list, i.e., from 0...n-1

In [26]:
df_final['isbn_order']=df_final['isbn'].apply(get_isbn_numeric_id)

In [27]:
df_final['userid_order']=df_final['user_id'].apply(get_user_numeric_id)
df_final.head()

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  isbn_order  userid_order  
0                2002            Ballantine Books           0             0  
1                2001                      Heinle           1             1  
2                1996                Warner Books           2             2  
3                1996                Warner Books           2             3  
4                1999  Cambridge University Press           3             4

Re-index the columns to build a matrix

In [28]:
new_col_order = ['userid_order','isbn_order','rating','book_title','book_author','year_of_publication','publisher',
                 'user_id','isbn']
df_final=df_final.reindex(columns = new_col_order)
df_final.head()

userid_order  isbn_order  rating            book_title      book_author  \
0             0           0       0  Flesh Tones: A Novel       M. J. Rose   
1             1           1       5      Rites of Passage       Judith Rae   
2             2           2       0          The Notebook  Nicholas Sparks   
3             3           2       0          The Notebook  Nicholas Sparks   
4             4           3       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  user_id        isbn  
0                2002            Ballantine Books   276725  034545104X  
1                2001                      Heinle   276726   155061224  
2                1996                Warner Books   276727   446520802  
3                1996                Warner Books   278418   446520802  
4                1999  Cambridge University Press   276729  052165615X

Split your data into two sets (training and testing)

In [29]:
from sklearn.model_selection import train_test_split
train_data,test_data = train_test_split(df_final,test_size=0.2)

Make predictions based on user and item variables

In [30]:
train_data_matrix = np.zeros((users,books))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1]=line[3]
    
test_data_matrix = np.zeros((users,books))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1]=line[3]

In [31]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric = 'cosine')
item_similarity = pairwise_distances(train_data_matrix.T, metric = 'cosine')

In [33]:
user_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

Making Predictions

In [34]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating=ratings.mean(axis=1)
        ratings_diff=(ratings-mean_user_rating[:,np.newaxis])
        pred=mean_user_rating[:,np.newaxis]+similarity.dot(ratings_diff)/np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred=ratings.dot(similarity)/np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [36]:
item_prediction=predict(train_data_matrix, item_similarity, type='item')
user_prediction=predict(train_data_matrix, user_similarity, type='user')

In [37]:
print(item_prediction)

[[0.         0.00062112 0.0006212  ... 0.00062169 0.00062112 0.00062112]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.06583851 0.06583851 0.06584669 ... 0.06589865 0.06583851 0.06583851]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [38]:
print(user_prediction)

[[-0.00140819 -0.00140819  0.00221938 ...  0.00947452 -0.00140819
  -0.00140819]
 [ 0.00401596 -0.00202999  0.00159758 ...  0.00885272 -0.00202999
  -0.00202999]
 [ 0.06992833  0.06388081  0.06750932 ...  0.07476634  0.06388081
   0.06388081]
 ...
 [ 0.00401596 -0.00202999  0.00159758 ...  0.00885272 -0.00202999
  -0.00202999]
 [ 0.00401596 -0.00202999  0.00159758 ...  0.00885272 -0.00202999
  -0.00202999]
 [ 0.00401596 -0.00202999  0.00159758 ...  0.00885272 -0.00202999
  -0.00202999]]


Evaluation

In [40]:
from sklearn.metrics import mean_squared_error
from math import sqrt

def rmse(prediction, ground_truth):
    prediction = prediction[ground_truth.nonzero()].flatten()
    ground_truth = ground_truth[ground_truth.nonzero()].flatten()
    return sqrt(mean_squared_error(prediction, ground_truth))

In [43]:
print('user based CF RMSE:' + str(rmse(user_prediction,test_data_matrix)))
print('item based CF RMSE:' + str(rmse(item_prediction,test_data_matrix)))

user based CF RMSE:7.70154995716364
item based CF RMSE:7.7007516346620495
